{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "b3fff751",
   "metadata": {},
   "source": [
    "#     STREAMLIT DASHBOARD - ENAP INTERNSHIP"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "ba3704be",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'streamlit'",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mModuleNotFoundError\u001b[39m                       Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[6]\u001b[39m\u001b[32m, line 1\u001b[39m\n\u001b[32m----> \u001b[39m\u001b[32m1\u001b[39m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mstreamlit\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mas\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mst\u001b[39;00m\n\u001b[32m      2\u001b[39m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mpandas\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mas\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mpd\u001b[39;00m\n\u001b[32m      3\u001b[39m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mnumpy\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mas\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mnp\u001b[39;00m\n",
      "\u001b[31mModuleNotFoundError\u001b[39m: No module named 'streamlit'"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import plotly.express as px"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c5e18382",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "\n",
    "# ============================================================\n",
    "# To run: streamlit run dashboard.py\n",
    "\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# PAGE CONFIG\n",
    "# ============================================================\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title=\"ENAP - Data Dashboard\",\n",
    "    page_icon=\"🎨\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "# ============================================================\n",
    "# HEADER\n",
    "# ============================================================\n",
    "\n",
    "st.title(\"🎨 ENAP - Tableau de Bord Analytique\")\n",
    "st.markdown(\"*Analyse exploratoire des données — Stage 2025*\")\n",
    "st.divider()\n",
    "\n",
    "# ============================================================\n",
    "# LOAD DATA\n",
    "# ============================================================\n",
    "\n",
    "@st.cache_data  # this makes it load faster after first run\n",
    "def load_data(file):\n",
    "    if file.name.endswith(\".csv\"):\n",
    "        return pd.read_csv(file, encoding=\"latin1\")\n",
    "    else:\n",
    "        return pd.read_excel(file)\n",
    "\n",
    "uploaded_file = st.file_uploader(\"📂 Charger votre fichier de données\", type=[\"csv\", \"xlsx\"])\n",
    "\n",
    "if uploaded_file:\n",
    "    df = load_data(uploaded_file)\n",
    "    st.success(f\"✅ Données chargées : {df.shape[0]} lignes, {df.shape[1]} colonnes\")\n",
    "\n",
    "    # ============================================================\n",
    "    # SIDEBAR FILTERS\n",
    "    # ============================================================\n",
    "\n",
    "    st.sidebar.header(\"🔧 Filtres\")\n",
    "\n",
    "    # Automatically detect categorical columns for filtering\n",
    "    categorical_cols = df.select_dtypes(include=\"object\").columns.tolist()\n",
    "    numerical_cols = df.select_dtypes(include=[\"int64\", \"float64\"]).columns.tolist()\n",
    "\n",
    "    # Dynamic filter for each categorical column\n",
    "    filters = {}\n",
    "    for col in categorical_cols[:3]:  # limit to first 3 to avoid clutter\n",
    "        unique_vals = df[col].dropna().unique().tolist()\n",
    "        selected = st.sidebar.multiselect(f\"Filtrer par {col}\", unique_vals, default=unique_vals)\n",
    "        filters[col] = selected\n",
    "\n",
    "    # Apply filters\n",
    "    df_filtered = df.copy()\n",
    "    for col, selected_vals in filters.items():\n",
    "        df_filtered = df_filtered[df_filtered[col].isin(selected_vals)]\n",
    "\n",
    "    # ============================================================\n",
    "    # SECTION 1 - OVERVIEW\n",
    "    # ============================================================\n",
    "\n",
    "    st.header(\"📊 Vue Générale\")\n",
    "\n",
    "    col1, col2, col3, col4 = st.columns(4)\n",
    "    col1.metric(\"Nombre de lignes\", df_filtered.shape[0])\n",
    "    col2.metric(\"Nombre de colonnes\", df_filtered.shape[1])\n",
    "    col3.metric(\"Valeurs manquantes\", df_filtered.isnull().sum().sum())\n",
    "    col4.metric(\"Doublons\", df_filtered.duplicated().sum())\n",
    "\n",
    "    st.subheader(\"Aperçu des données\")\n",
    "    st.dataframe(df_filtered.head(20), use_container_width=True)\n",
    "\n",
    "    # ============================================================\n",
    "    # SECTION 2 - MISSING VALUES\n",
    "    # ============================================================\n",
    "\n",
    "    st.header(\"🔍 Valeurs Manquantes\")\n",
    "\n",
    "    missing = df_filtered.isnull().sum()\n",
    "    missing = missing[missing > 0]\n",
    "\n",
    "    if missing.empty:\n",
    "        st.success(\"✅ Aucune valeur manquante détectée !\")\n",
    "    else:\n",
    "        fig = px.bar(\n",
    "            x=missing.index,\n",
    "            y=missing.values,\n",
    "            labels={\"x\": \"Colonne\", \"y\": \"Valeurs manquantes\"},\n",
    "            color=missing.values,\n",
    "            color_continuous_scale=\"reds\",\n",
    "            title=\"Valeurs manquantes par colonne\"\n",
    "        )\n",
    "        st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "    # ============================================================\n",
    "    # SECTION 3 - DISTRIBUTIONS\n",
    "    # ============================================================\n",
    "\n",
    "    st.header(\"📈 Distributions\")\n",
    "\n",
    "    if numerical_cols:\n",
    "        selected_num_col = st.selectbox(\"Choisir une colonne numérique\", numerical_cols)\n",
    "\n",
    "        col1, col2 = st.columns(2)\n",
    "\n",
    "        with col1:\n",
    "            fig = px.histogram(df_filtered, x=selected_num_col, nbins=30,\n",
    "                               title=f\"Distribution de {selected_num_col}\",\n",
    "                               color_discrete_sequence=[\"steelblue\"])\n",
    "            st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "        with col2:\n",
    "            fig = px.box(df_filtered, y=selected_num_col,\n",
    "                         title=f\"Boxplot de {selected_num_col}\",\n",
    "                         color_discrete_sequence=[\"lightcoral\"])\n",
    "            st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "    # ============================================================\n",
    "    # SECTION 4 - CATEGORICAL ANALYSIS\n",
    "    # ============================================================\n",
    "\n",
    "    st.header(\"🗂️ Analyse Catégorielle\")\n",
    "\n",
    "    if categorical_cols:\n",
    "        selected_cat_col = st.selectbox(\"Choisir une colonne catégorielle\", categorical_cols)\n",
    "        top_n = st.slider(\"Nombre de valeurs à afficher\", 5, 20, 10)\n",
    "\n",
    "        top_vals = df_filtered[selected_cat_col].value_counts().head(top_n)\n",
    "\n",
    "        fig = px.bar(\n",
    "            x=top_vals.index,\n",
    "            y=top_vals.values,\n",
    "            labels={\"x\": selected_cat_col, \"y\": \"Count\"},\n",
    "            title=f\"Top {top_n} valeurs — {selected_cat_col}\",\n",
    "            color=top_vals.values,\n",
    "            color_continuous_scale=\"blues\"\n",
    "        )\n",
    "        st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "    # ============================================================\n",
    "    # SECTION 5 - CORRELATION MATRIX\n",
    "    # ============================================================\n",
    "\n",
    "    st.header(\"🔗 Matrice de Corrélation\")\n",
    "\n",
    "    if len(numerical_cols) > 1:\n",
    "        corr = df_filtered[numerical_cols].corr()\n",
    "\n",
    "        fig = px.imshow(\n",
    "            corr,\n",
    "            text_auto=\".2f\",\n",
    "            color_continuous_scale=\"RdBu_r\",\n",
    "            title=\"Corrélation entre variables numériques\"\n",
    "        )\n",
    "        st.plotly_chart(fig, use_container_width=True)\n",
    "    else:\n",
    "        st.info(\"Pas assez de colonnes numériques pour une matrice de corrélation.\")\n",
    "\n",
    "    # ============================================================\n",
    "    # SECTION 6 - TIME SERIES (if date column exists)\n",
    "    # ============================================================\n",
    "\n",
    "    st.header(\"📅 Analyse Temporelle\")\n",
    "\n",
    "    date_cols = [col for col in df_filtered.columns if \"date\" in col.lower()\n",
    "                 or \"année\" in col.lower() or \"mois\" in col.lower()]\n",
    "\n",
    "    if date_cols and numerical_cols:\n",
    "        date_col = st.selectbox(\"Colonne date\", date_cols)\n",
    "        value_col = st.selectbox(\"Valeur à suivre\", numerical_cols)\n",
    "\n",
    "        try:\n",
    "            df_time = df_filtered.copy()\n",
    "            df_time[date_col] = pd.to_datetime(df_time[date_col])\n",
    "            df_time = df_time.sort_values(date_col)\n",
    "\n",
    "            fig = px.line(df_time, x=date_col, y=value_col,\n",
    "                          title=f\"Évolution de {value_col} dans le temps\")\n",
    "            st.plotly_chart(fig, use_container_width=True)\n",
    "        except:\n",
    "            st.warning(\"Impossible de convertir cette colonne en date.\")\n",
    "    else:\n",
    "        st.info(\"Aucune colonne date détectée — section ignorée.\")\n",
    "\n",
    "    # ============================================================\n",
    "    # SECTION 7 - EXPORT\n",
    "    # ============================================================\n",
    "\n",
    "    st.header(\"💾 Exporter les données nettoyées\")\n",
    "\n",
    "    df_clean = df_filtered.drop_duplicates()\n",
    "\n",
    "    csv = df_clean.to_csv(index=False).encode(\"utf-8\")\n",
    "    st.download_button(\n",
    "        label=\"📥 Télécharger les données nettoyées (CSV)\",\n",
    "        data=csv,\n",
    "        file_name=\"enap_clean_data.csv\",\n",
    "        mime=\"text/csv\"\n",
    "    )\n",
    "\n",
    "else:\n",
    "    st.info(\"👆 Veuillez charger un fichier pour commencer l'analyse.\")\n",
    "    st.markdown(\"\"\"\n",
    "    ### Comment utiliser ce dashboard ?\n",
    "    1. Cliquez sur **Browse files** et chargez votre fichier Excel ou CSV\n",
    "    2. Utilisez les **filtres** dans la barre latérale pour explorer les données\n",
    "    3. Naviguez entre les sections pour analyser votre dataset\n",
    "    \"\"\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
